name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' al nombre de tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Selecciona la versión de Python que necesites

    - name: Install dependencies
      run: pip install -r requirements.txt  # Asegúrate de tener un archivo requirements.txt

    - name: Build site
      run: |
        # Cambia estos comandos según la estructura de tu proyecto
        cd FISICA
        python app.py build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: FISICA  # Carpeta que contiene tu sitio web generado
