name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto al nombre de la rama principal de tu repositorio

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Puedes cambiar la versión de Python si es necesario

      - name: Install dependencies
        run: |
          cd FISICA  # Cambia al directorio FISICA
          pip install -r requirements.txt

      - name: Build site
        run: |
          cd simulador.github.io  # Cambia al directorio FISICA
          # Aquí puedes agregar comandos adicionales para construir tu sitio si es necesario

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: simulador.github.io
  # Directorio que contiene tus archivos HTML, CSS, etc.
