name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Elige la versión de Python que necesitas

    - name: Install dependencies
      run: |
        pip install mkdocs
        pip install mkdocs-material  # Opcional: instala un tema de mkdocs
      working-directory: ./

    - name: Build site
      run: mkdocs build --clean
      working-directory: ./
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site  # Directorio donde mkdocs generó la documentación
