name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' al nombre de tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Cambia a la versión de Python que necesites

    

      - name: Build and deploy
        run: |
          mkdocs build --clean
        working-directory: ./  # La carpeta principal del proyecto es la raíz del repositorio

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Cambia a la versión más reciente disponible
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # Carpeta donde MkDocs genera el sitio
